services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: ./Dockerfile.dev
        volumes:
            - ./app/:/code/app
        ports:
            - 6060:6060
        networks:
            - app_network
        depends_on:
            - db
        env_file:
            - ./.env
    db:
        image: postgres
        container_name: db
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=app_db
        networks:
            - app_network
        volumes:
            - database:/var/lib/postgresql/data
        ports:
            - 5432:5432
        restart: unless-stopped

networks:
    app_network:
        driver: bridge

volumes:
    database:
        external: false
